/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peridot.Archiver;

import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.SystemUtils;
import peridot.Log;
import java.io.File;
import java.net.URI;
import java.net.URL;
import java.security.CodeSource;
import java.security.ProtectionDomain;
import java.util.logging.Level;

/**
 * Archiver.Places determines, creates and stores important global files and directories of R-Peridot.
 * @author pentalpha
 */
public final class Places {
    /**
     * The master directory where all the user stuff is stored.
     * But its not the place where r-peridot is, that's the jarFolder.
     */
    public static File peridotDir = new File(getUserHomePath() + File.separator
            + ".r-peridot-files");

    /**
     * The place where all the results generated by the modules are saved after analysis.
     */
    public static File finalResultsDir = new File(getUserHomePath() + File.separator 
            + ".r-peridot-files" 
            + File.separator + "results");

    /**
     * The place where all the modules available to the user are stored, each on
     * it's own directory.
     */
    public static File scriptsDir = new File(getUserHomePath() + File.separator 
            + ".r-peridot-files" 
            + File.separator + "scripts");

    /**
     * The directory of r-portable, if there is a detectable r-portable on this system.
     */
    public static File rPortableDir = getRPortableFolder();

    /**
     * The name of the file that stores the count reads for the modules to use.
     */
    public static String countReadsInputFileName = "rna-seq-input.tsv";

    /**
     * The file that stores the count reads for the modules to use.
     */
    public static File countReadsInputFile = new File(getUserHomePath() + File.separator
            + ".r-peridot-files" 
            + File.separator + "results" 
            + File.separator + countReadsInputFileName);

    /**
     * The name of the file that describes what is the condition of each sample.
     */
    public static String conditionInputFileName = "condition-input.tsv";

    /**
     * The file that describes what is the condition of each sample.
     */
    public static File conditionInputFile = new File(getUserHomePath() + File.separator 
            + ".r-peridot-files" 
            + File.separator + "results" 
            + File.separator + conditionInputFileName);

    /**
     * The R executable to be used by R-Peridot.
     */
    public static File rExec = getRExec();

    /**
     * The directory in which r-peridot is located.
     */
    public static File jarFolder = getJarFolder();

    /**
     * The directory where the defaults module, that can be loaded to scriptsDir, are stored.
     * If [jarFolder]/r-peridot-scripts is not present, its null.
     */
    public static File defaultModulesDir = getDefaultModulesDir();

    private Places(){
        throw new AssertionError();
    }

    /**
     *
     * @return The current user's home directory.
     */
    public static String getUserHomePath(){
        return System.getProperty("user.home");
    }

    /**
     * Creates peridotDir and finalResultsDir, if they do not yet.
     */
    public static void createPeridotDir(){
        if(peridotDir.exists() == false){
            Log.logger.info("~/r-peridot-files not found, creating it.");
            peridotDir.mkdirs();
            peridotDir.mkdir();
            if(!peridotDir.exists()){
                Log.logger.severe("Error: Could not create " + peridotDir.getAbsolutePath());
            }
        }
        if(finalResultsDir.exists() == false){
            Log.logger.info("Results directory not found, creating it.");
            finalResultsDir.mkdirs();
            finalResultsDir.mkdir();
            if(!finalResultsDir.exists()){
                Log.logger.severe("Error: Could not create directory for final results it");
            }
        }
    }

    /**
     * @return The directory where the default modules are stored. If does not exists, returns null.
     */
    public static File getDefaultModulesDir(){
        File file = new File(Places.jarFolder.getAbsolutePath() +
                            File.separator + "r-peridot-scripts");
        if(file.exists()){
            return file;
        }else{
            Log.logger.warning("Warning: No DefaultModulesDir found, without it you can't " +
                    "reload the modules.");
            return null;
        }
    }

    /**
     * Update each of the modules in scriptsDir, based on the modules in defaultModulesDir.
     * If scriptsDir does not exist, creates it.
     * If failed to update anything, Logs the exception.
     * @param overwrite True to force the update of modules
     *                  if they already exist in scriptsDir.
     */
    public static void updateModulesDir(boolean overwrite){
        try{
            if(scriptsDir.exists() == false){
                scriptsDir.mkdir();
            }
            updateModulesFolder(overwrite);
        }
        catch(Exception ex){
            Log.logger.severe("Error: could not update modules folder.");
            Log.logger.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }

    /**
     * 1. Gets the subdirectories of defaultModulesDir;
     * 2. For each subdirectory (that is not the .git folder),
     * Verifies if the equivalent subdirectory already existed in scriptsDir
     * and, if it did not, copies it to scriptsDir, only overwriting the
     * module already on scripts dir if overwrite = true.
     *
     * @param overwrite If already loaded modules should be overwritten.
     * @throws Exception
     */
    private static void updateModulesFolder(boolean overwrite) throws Exception{
        File[] modules = defaultModulesDir.listFiles();

        for(int i = 0; i < modules.length; i++){
            if(modules[i].isDirectory()
            && modules[i].getParentFile().getAbsolutePath().equals(defaultModulesDir.getAbsolutePath())
            && modules[i].getName().contains(".git") == false)
            {
                File targetDir = new File(scriptsDir.getAbsolutePath()
                                    + File.separator + modules[i].getName());

                if(targetDir.exists()){
                    if(overwrite){
                        FileUtils.deleteDirectory(targetDir);
                        FileUtils.copyDirectory(modules[i], targetDir);
                        Log.logger.info("Updated " + modules[i].getName() + ".");
                    }
                }else{
                    FileUtils.copyDirectory(modules[i], targetDir);
                    Log.logger.info("Updated " + modules[i].getName() + ".");
                }
            }
        }

        File gitDir = new File(scriptsDir.getAbsolutePath() + File.separator + ".git");
        if(gitDir.exists()){
            FileUtils.deleteDirectory(gitDir);
        }
    }

    /**
     * Determines where r-portable may be isntalled
     * Looks for a ./r-portable/ folder or for a ~/r-portable folder.
     * @return  The directory in which r-peridot is located.
     *          null if could not find it.
     */
    public static File getRPortableFolder(){
        File userRPortable = new File(getUserHomePath() + File.separator 
            + "r-portable");
        File jarFolder = getJarFolder();
        File localRPortable = new File(jarFolder.getAbsolutePath() + File.separator
                + "r-portable");
        
        if(localRPortable.exists()){
            //Log.logger.info("Local r-portable folder found.");
            return localRPortable;
        }else if (userRPortable.exists()){
            //Log.logger.warning("Warning: Local r-portable folder not found.");
            //Log.logger.info("User r-portable folder found.");
            return userRPortable;
        }else{
            //Log.logger.severe("Error: No r-portable found");
            return null;
        }
    }

    /**
     * @return  The place where the current .jar executable is located.
     *          If the .jar is embedded in an .exe, returns the parent directory.
     */
    public static File getJarFolder(){
        File jarFolder = null;
        ProtectionDomain pDomain = Places.class.getProtectionDomain();
        CodeSource cSource = pDomain.getCodeSource();
        URL url = cSource.getLocation();
        URI uri = null;
        try{
            uri = url.toURI();
            jarFolder = new File(uri.getPath());
            if(jarFolder.isFile()){
                File parent = jarFolder.getParentFile();
                jarFolder = parent;
            }
            return jarFolder;
        }catch(Exception ex){
            ex.printStackTrace();
            Log.logger.severe("Error: Could not load jar location");
            Log.logger.log(Level.SEVERE, ex.getMessage(), ex);
            return null;
        }
        
    }

    /**
     * Looks for the R executable file in [rPortableDir]/bin,
     * choosing the right one based on the current processor architecture and OS.
     *
     * @return  The R executable file.
     *          null if could not find it.
     */
    public static File getRExec(){
        boolean is64Bits = false;
        if(SystemUtils.OS_ARCH.contains("64")){
            is64Bits = true;
        }
        String path1 = "";
        String path2 = "";
        if(Places.rPortableDir != null){
            path1 = rPortableDir.getAbsolutePath() + File.separator + "bin";
            if(SystemUtils.IS_OS_WINDOWS){
                path2 = rPortableDir.getAbsolutePath() + File.separator + "bin";
                if(is64Bits == true){
                    path1 += File.separator +"x64";
                    path2 += File.separator +"i386";
                }else{
                    path1 += File.separator + "i386";
                }
                path1 += File.separator + "R.exe";
                path2 += File.separator + "R.exe";
            }else if(SystemUtils.IS_OS_LINUX){
                path2 = rPortableDir.getAbsolutePath();
                path1 += File.separator + "R";
                path2 += File.separator + "R";
            }
        }
        
        File exec = new File(path1);
        File exec2 = new File(path2);
        if(exec.exists() == false || exec.isDirectory()){
            exec = exec2;
        }
        if(exec.exists()){
            if(exec.isFile()){
                Log.logger.fine("R is " + exec.getAbsolutePath());
                if(SystemUtils.IS_OS_LINUX){
                    //setLinuxEnvironmentVars();
                }
                return exec;
            }
        }
        Log.logger.warning("R portable not found, using system PATH instead.");
        return null;
    }

    /**
     * @return Array of Linux Environment Variables for R-Portable.
     */
    public static String[] getLinuxEnvForRPortable(){
        String[] strings = {"R_HOME='" + Places.rPortableDir.getAbsolutePath() + "'"};
        return strings;
    }
}
